require('plugins')
require('basic')
require('keybindings')

require('plugin-config/nvim-gps')
require('plugin-config/nvim-tree')
require('plugin-config/telescope')
require('plugin-config/lualine')
require('plugin-config/bufferline')
require('plugin-config/gitsigns')
require('plugin-config/autosave')

require('plugin-config/nvim-treesitter')
require('lsp/tabnine')
require('lsp/setup')
require('lsp/nvim-cmp')
